### ISSUE TITLE
Error when sent /addmemory

### ISSUE THREAD

**Issue by egcash** [HexyeDEV/Telegram-Chatbot-Gpt4Free#6]
Unhandled exception on addmemory
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/updates.py", line 497, in _dispatch_update
    await callback(event)
  File "/root/Telegram-Chatbot-Gpt4Free/main.py", line 142, in addmemory
    text = event.text.split(' ', 1)[1]
IndexError: list index out of range

**Comment by HexyeDEV** [comment]
you must also provide the data that you want to keep in Memory. for example: /addmemory Today's Bitcoin price is 25000$.

**Comment by egcash** [comment]
Thanks
